// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/empinfo": {
            "get": {
                "description": "Returns employees with department and bio info",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Get employee info",
                "parameters": [
                    {
                        "type": "string",
                        "default": "",
                        "description": "Department name to filter by",
                        "name": "Dept",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "",
                        "description": "Filter by Emp Name to filter by",
                        "name": "FilterName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.EmpInfo"
                            }
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Returns a list of employees",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Get employees",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Number of records to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Number of records to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Employee"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.EmpInfo": {
            "type": "object",
            "properties": {
                "BioID": {
                    "type": "string"
                },
                "Dept": {
                    "type": "string"
                },
                "IdNo": {
                    "type": "string"
                },
                "Name": {
                    "type": "string"
                }
            }
        },
        "main.Employee": {
            "type": "object",
            "properties": {
                "fname": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lname": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9090",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "My Go API",
	Description:      "My first Go API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
